### ISSUE TITLE
Formatting does not work correctly

### ISSUE THREAD

**Issue by xulongwu4** [neoclide/coc-json#10]
I created a simple `json` file with the following content:
```json
[
    {
    "link": {
        "bashrc": "~/.bashrc"
        }
    }
]
```

Then I tried to use `coc-json` to format it. The result is as follows:
```json
[
    {
        "link": {
            "bashrc": "~/.bashrc"
        }
    }
]
    "link": {
        "bashrc": "~/.bashrc"
        }
    }
]
```

The formatted document has some part of text dupliated and has an extra right bracket.

**Comment by chemzqm** [comment]
Could be bug, but I can't reproduce

**Comment by xulongwu4** [comment]
I can reproduce this issue on two different OSes: Solus and void linux, both with vim 8.1.1764 though.

**Comment by patrick96** [comment]
I was able to reproduce this just now (vim 8.1.2268). I created a minimal config and was good to go, then I remembered I should maybe update my vim plugins. Now I can't reproduce this anymore, so this was probably fixed in a version of coc.nvim
