### ISSUE TITLE
tsconfig.json [json 521] [e] Comments are not permitted in JSON.

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc-json#11]
I suggest adding the ability to configure exceptions in the rules for some files.

**Comment by chemzqm** [comment]
Send your feature request to json language service.

**Comment by forest0** [comment]
Actually, vscode-json-languageservice support this extension.

But you need to add `"allowComments": true` to the schema file.

@dementor5

**Comment by alextes** [comment]
@forest0 can you describe what you mean by 'the schema file'?

**Comment by chemzqm** [comment]
You can configure your vim to make that file with jsonc filetype to allow comment.

**Comment by alextes** [comment]
@chemzqm yea that's what I ended up doing instead, thanks for pointing it out 🙏 .

For others reading along I installed `'neoclide/jsonc.vim'` and pointed out to vim that `tsconfig.json` is really a jsonc file.
```
" tsconfig.json is actually jsonc, help TypeScript set the correct filetype
autocmd BufRead,BufNewFile tsconfig.json set filetype=jsonc
```
