### ISSUE TITLE
coc-json extension doesn't seem to be doing anything

### ISSUE THREAD

**Issue by masaeedu** [neoclide/coc-json#17]
Hello. There's something funny going on with my extensions ever since I switched from using vim plug to install them to using the `g:coc_global_extensions` variable. Here's the relevant configuration I have right now:

```
if has('nvim')
  Plug 'neoclide/coc.nvim', { 'do': 'yarn install --frozen-lockfile' }
endif

" Completion: language-specific
if has('nvim')
  let g:coc_global_extensions = [ 'https://github.com/neoclide/coc-tsserver'
                              \ , 'https://github.com/neoclide/coc-json'
                              \ , 'https://github.com/neoclide/coc-java'
                              \ , 'https://github.com/neoclide/coc-snippets'
                              \ , 'https://github.com/masaeedu/coc-omnisharp'
                              \ , 'https://github.com/neoclide/coc-yaml'
                              \ , 'https://github.com/iamcco/coc-vimlsp'
                              \ ]
endif
```

However when I try to work with a JSON file it doesn't look like any of the features are working: https://asciinema.org/a/97pUN7wSQa6ah3PJEuqTrVOu7 (sorry about small font size, please zoom out a bit to fit to screen)

**Comment by fannheyward** [comment]
What does `:CocList extensions` output?

**Comment by masaeedu** [comment]
@fannheyward It outputs the list of all the extensions from my `coc_global_extensions` variable, with the `coc-json` and `coc-snippets` extensions having an asterisk next to them.

**Comment by fannheyward** [comment]
Looks like extensions are installed successfully. Can you provide a mini vimrc to reproduce this issue?

**Comment by chemzqm** [comment]
Use extenison name instead of url in ` g:coc_global_extensions`

**Comment by masaeedu** [comment]
@chemzqm The documentation [here](https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#install-extensions) indicates that using the full URL of an extension is supported when using `CocInstall`:

> The extension name can also be the url of a git repository, like: `https://github.com/andys8/vscode-jest-snippets` which could be accepted by `yarn install`.

Does `g:coc_global_extensions` not work the same way? If not, how should one install extensions from a fork?

**Comment by chemzqm** [comment]
You should use plugin manager of vim, read wiki.
