### ISSUE TITLE
Missing property "pages"

### ISSUE THREAD

**Issue by pbnj** [neoclide/coc-json#18]
coc-json seems to be reporting a warning on `app.json` that I don't know where it is coming from.

I verified that coc-json is reporting this warning because after disabling coc-json, I don't get the warning. See screenshots 1 & 2 below.

I have checked the schemastore repository looking for any `app.json` in `fileMatch`, but didn't find any ([ref](https://github.com/SchemaStore/schemastore/search?q=%22app.json%22&unscoped_q=%22app.json%22)).

## Reproduction Steps

In neovim:

- `:e app.json`
- go into insert mode <kbd>i</kbd>, type `{}`, go back to normal mode <kbd>ESC</kbd>, and save `:w`
- warning shows up

## Screenshot 1
![Screen Shot 2020-02-25 at 4 20 36 PM](https://user-images.githubusercontent.com/6811830/75299809-e68a2b80-57ea-11ea-9ab2-ed786fb33f6c.png)

## Screenshot 2
![Screen Shot 2020-02-25 at 4 20 56 PM](https://user-images.githubusercontent.com/6811830/75299989-6c0ddb80-57eb-11ea-994e-d0ca7bc55eed.png)

**Comment by chemzqm** [comment]
It's builtin support for wechat miniprogram, I've made a fix.
