### ISSUE TITLE
Incorrect type. Expected "array". in manifest.json

### ISSUE THREAD

**Issue by lucasholder** [neoclide/coc-json#19]
For some reason, I'm getting a weird error when opening a [Chrome extension manifest file](https://developer.chrome.com/extensions/manifest):

```
Incorrect type. Expected "array". 
```

<img width="668" alt="Screenshot 2020-03-12 19 23 38" src="https://user-images.githubusercontent.com/62086489/76575993-30d00580-6497-11ea-977e-18cbb2a58db2.png">

What is causing this?

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc-json/blob/master/src/catalog.json#L80

**Comment by chemzqm** [comment]
You can use `"$schema"` in your json or `json.schemas` in coc-settings.json to fix this problem.

**Comment by hankchiutw** [comment]
I added this in coc-settings.json but still got the warning:
```json
"json.schemas": [
  {
    "fileMatch": ["manifest.json"],
    "url": "https://json.schemastore.org/chrome-manifest"
  }
]
```

It seems because my `json.schemas` doesn't override the default settings.

If I'm not wrong, the warning comes from this schema: https://github.com/neoclide/coc-json/blob/master/src/catalog.json#L1563

**Comment by everdimension** [comment]
> It seems because my json.schemas doesn't override the default settings.

Same problem here

**Comment by furopi** [comment]
For me the error was lying in the "Apache Conf Snippets"-Extension. Just leaving that here if someone is having the same issue...
