### ISSUE TITLE
Disable diagnostics

### ISSUE THREAD

**Issue by nomasprime** [neoclide/coc-json#24]
How can I disable diagnostics?

**Comment by chemzqm** [comment]
`:h coc-config-diagnostic`

**Comment by nomasprime** [comment]
Thanks @chemzqm.

**Comment by YorickPeterse** [comment]
@chemzqm I tried this out, but it appears that when `diagnostic.enable` is set to `false`, coc-json still produces diagnostics when typing. Is there a way to configure coc-json so it only produces diagnostics after writing to the file?

**Comment by chemzqm** [comment]
No
