### ISSUE TITLE
Allowing comments example

### ISSUE THREAD

**Issue by julian-payne** [neoclide/coc-json#27]
In the README we have: 
> How to suppress error [json 521] [e] Comments are not permitted in JSON?
> You can configure your vim to make that file with jsonc filetype to allow comment.

Can I please have an example of this configuration?

Many thanks for this awesome project :)

**Comment by chemzqm** [comment]
The filetype need to be jsonc.

**Comment by julian-payne** [comment]
> The filetype need to be jsonc.

Sure.
"Can I please have an example of this configuration?"

What I mean is, what does this look like in `.vimrc` or `init.nvim`?

**Comment by Qyriad** [comment]
To make Vim treat all json files as jsonc:
```vim
augroup JsonToJsonc
    autocmd! FileType json set filetype=jsonc
augroup END
```
Or you can use a modeline (`:help modeline`) at the very top or bottom of an individual json file, to set the filetype to jsonc for only that file:
```json
// vim: ft=jsonc
```

**Comment by chemzqm** [comment]
There's https://github.com/neoclide/jsonc.vim which set jsonc filetype for file with `.cjson` as extension.

**Comment by julian-payne** [comment]
> To make Vim treat all json files as jsonc:
> 
> ```viml
> augroup JsonToJsonc
>     autocmd! FileType json set filetype=jsonc
> augroup END
> ```
> 
> Or you can use a modeline (`:help modeline`) at the very top or bottom of an individual json file, to set the filetype to jsonc for only that file:
> 
> ```json
> // vim: ft=jsonc
> ```

Thank you so much!!
Extremely helpful!
