### ISSUE TITLE
Schema Error for Windows Terminal Settings

### ISSUE THREAD

**Issue by ca-mantis-shrimp** [neoclide/coc-json#28]
Hello All, 

I'm trying to use coc.json to edit my settings.json for the windows terminal. 

Most everything works fine, only it throws a "schemas are not fully supported yet" error (pictured below)

![image](https://user-images.githubusercontent.com/25948785/97516956-47fa2f80-1962-11eb-82b5-cfd639d9abf5.png)

Do we know when this will be supported? 

Thanks for your wonderful plugin, I appreciate your time and expertise.

**Comment by chemzqm** [comment]
It's warning, you need ask developer of vscode-json-languageservice.
