### ISSUE TITLE
Format provider not found for file

### ISSUE THREAD

**Issue by perfectspr** [neoclide/coc-json#33]
cloud not format json file when saving it. error message from coc log:
```
Format provider not found for file
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by fannheyward** [comment]
Reproduced, coc-json doesn't has `documentFormattingProvider`. Latest coc will check provider at `willSaveWaitUntil`.

**Comment by fannheyward** [comment]
Steps:

1. `"coc.preferences.formatOnSaveFiletypes": ["json", "jsonc"]`
2. save JSON file

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
