### ISSUE TITLE
Property is not allowed in coc-settings.json

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [neoclide/coc-json#34]
I've just installed coc-json in my vim setup and i get `[json] [W] Property explorer is not allowed.`  on some words in the local coc-settings.json file.

## What happens
Some terms like "explorer", "yaml" and "json" in coc-settings.json trigger Property explorer is not allowed.

![image](https://user-images.githubusercontent.com/37159012/102410076-5541ab00-3ff0-11eb-8273-e72f59e02b82.png)

## What should happen
Words like "explorer", "yaml" and "json" should be valid.

## Extra notes
- These keywords refer to coc modules installed using `:CocInstall coc-yaml coc-json coc-explorer.`

**Comment by chemzqm** [comment]
You don't have them installed

**Comment by fannheyward** [comment]
You should use `"json.enable": true` etc.

**Comment by FedericoAntoniazzi** [comment]
> You don't have them installed

Indeed they are installed.

**Comment by chemzqm** [comment]
You have to use supported keys only.
