### ISSUE TITLE
support portable schema config

### ISSUE THREAD

**Issue by zanona** [neoclide/coc-json#41]
I am not sure if this is currently the case with `jsonValidation` under a project's `package.json` file, as I have tried, and it didn't seem to have an effect. But it would be great if we could be able to link schemas on a project-level, so references are portable.

For example

```jsonc
// /home/user/src/my-app/package.json
{
  "name": "my-app",
  "version": "0.0.0",
  "contributes": {
    "jsonValidation": [
      // this links to both json and schema on my project's `./assets` directory
      { "url": "assets/selectors.schema.json", "fileMatch": "assets/selectors.json" }
    ]
  }
}
```

With the above, validations are carried within the project directory and can be used on different environments independently of their  `./.vim/coc-settings.json` configuration, which wouldn't be needed.

This could also help package developers to use these `package.json` fields in order to run validation on CI level by reading the `contributes.jsonValidation` entries against the schemas defined.

**Comment by chemzqm** [comment]
Does VSCode have support for that?

**Comment by zanona** [comment]
As a matter of fact, indeed, it doesn't. By the time I created this issue, I wasn't fully aware of the goal of the project and its 1:1 relation to VS Code. Let me close this now, as it feels a bit out of scope now. Sorry for the noise.
