### ISSUE TITLE
Feature Suggestion: Make trailingComma ignorable by a configuration variable

### ISSUE THREAD

**Issue by lanza** [neoclide/coc-json#42]
Trailing commas have grown quite popular at this point. This warning could be toggleable.

**Comment by chemzqm** [comment]
We don't filter diagnostics, needs https://github.com/Microsoft/vscode-json-languageservice support that first.

**Comment by lf-** [comment]
I believe that that one does support handling trailing commas and comments, but it might require some changes in the schemas.

**Comment by TonalidadeHidrica** [comment]
Excuse me, I want to disable "trailing comma" diagnostics too.  Is there a way to disable it right now, or does it need some extra enhancement to either `coc-json` or `vscode-json-languageservice`?  In any case, why was this issue closed?

**Comment by lanza** [comment]
Somebody would have to implement it in `vscode-json-languageservice` and then import it here.

**Comment by chemzqm** [comment]
Checkout https://github.com/microsoft/vscode-json-languageservice/issues/115, change the filetype to jsonc or create custom schema with `allowTrailingCommas` to `true`.
