### ISSUE TITLE
Extension-related items doesn't exist in Autocompletion list (version from 1.3.0)

### ISSUE THREAD

**Issue by lchtao26** [neoclide/coc-json#46]
### Desc
1. `:CocConfig` open the coc-settings.json
2. I have installed some coc extensions like `coc-prettier`, `coc-eslint`, but I can't get those related items in the autocompletion popup list while I'm tying.
3. When I install `coc-json@1.2.6`, everything is fine, but version from 1.30 has this issue.

### Env
neovim: v0.44
coc-json: ^1.3.0

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
