### ISSUE TITLE
Unable to disable schema

### ISSUE THREAD

**Issue by notpeelz** [neoclide/coc-json#50]
I have a file named `app.json`, which is getting incorrectly detected as an "Expo SDK" file.
Is there a way to disable that schema from the builtin catalog?

I tried to override it through the `json.schemas` setting, but to no avail:
```json
"json.schemas": [
  { "fileMatch": ["app.json"], "url": "" }
]
```

**Comment by chemzqm** [comment]
You need to provider valid url.

**Comment by notpeelz** [comment]
I don't want to replace the url; I want to remove that schema rule altogether. Is there a way to do that?
