### ISSUE TITLE
json5 support

### ISSUE THREAD

**Issue by FernandoBasso** [neoclide/coc-json#54]
When I set the filetype of my buffer to [json5] (either vim or nvim), then I don't get intellisense and the other goodies.

Is it possible to make this package also support json5 or we would have to create a dedicated `coc-json5` plugin?

**Comment by chemzqm** [comment]
`:h g:coc_filetype_map` might helps.

**Comment by giggio** [comment]
This issue should be reopened. Setting files to `json` or `jsonc` does not work, comments are not allowed, single quotes neither etc:

```vim
let g:coc_filetype_map = {
      \ 'json5': 'json',
      \ }
```

So this is not an actual workaround. Or, as mentioned by OP, another plugin should be created, as this might be out of scope of this one.

![Image](https://github.com/user-attachments/assets/b7e5a753-086e-4f67-b39f-8c5a6f3d1a0e)

**Comment by chemzqm** [comment]
Comments are allowed with `jsonc`, not others, need the language server support them.
