### ISSUE TITLE
Add support for `.hjson` and `.json5` types.

### ISSUE THREAD

**Issue by dessalines** [neoclide/coc-json#59]
[hjson](https://hjson.github.io/) especially is a popular format for config files, allows comments and such.

**Comment by wgwz** [comment]
it'd be cool if there was a config value that allows you to add different filetype extensions which coc-json will attempt to parse. i'm particularly interested in a `.jsonld` extension.

**Comment by chemzqm** [comment]
`:h g:coc_filetype_map`

**Comment by wgwz** [comment]
@chemzqm i tried adding the following to my vimrc today but it doesn't seem to be working, would offer some guidance on what i might being wrong?

i tried two different ways:

```
let g:coc_filetype_map = {
  \ 'json.jsonld': 'json',
  \ }
```

```
let g:coc_filetype_map = {
  \ 'jsonld': 'json',
  \ }
```

**Comment by chemzqm** [comment]
Try `:CocCommand document.echoFiletype`

**Comment by wgwz** [comment]
@chemzqm It doesn't return anything when I run that within a jsonld file..

**Comment by chemzqm** [comment]
Seems you don't have fieltype for the buffer, see `:h 'filetype''`

**Comment by wgwz** [comment]
@chemzqm awesome, this worked and thank you!

```
au BufRead,BufNewFile *.jsonld setfiletype json
let g:coc_filetype_map = {
  \ 'jsonld': 'json',
  \ }
```

[Ref](https://stackoverflow.com/questions/11666170/persistent-set-syntax-for-a-given-filetype)
