### ISSUE TITLE
coc-json deactivates coc-highlight color highlighting

### ISSUE THREAD

**Issue by cody-hou** [neoclide/coc-json#63]
After installing coc-json, color highlighting provided by coc-highlight stops working. I have set `coc-settings.json` to `"colors.filetypes": [*]` and confirmed that coc-highlight works on my vim install. Adding `".json"` to the file types did not resolve the issue.

**Comment by cody-hou** [comment]
Adding a few more details as requested: using Vim 9.0 installed via Homebrew on a M1 Pro Macbook Pro. `coc-nvim` installed via Vim native packages. Running `coc-highlight`, `coc-json`, and `coc-pyright` installed via `:CocInstall`. `coc-settings.json` only configured as above with `"colors.filetypes"`. Thanks!

**Comment by chemzqm** [comment]
@cody-hou What is the code(with color) like?

**Comment by cody-hou** [comment]
I'm using hex values in a file named `config.json` as follows:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/106495649/186431420-54493d78-db3a-4847-8bb3-f56f9d4a3375.png">

I opened a `test.json` document and here's what `:CocList extensions` shows:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/106495649/186430940-413573c5-1dbc-4eec-9e01-d4cb84e5a70c.png">

**Comment by chemzqm** [comment]
Need to be fixed by `documentColorManager` of coc.nvim, the results should be merged.

**Comment by chemzqm** [comment]
It's already fixed, please upgrade to the latest release branch of coc.nvim.
