### ISSUE TITLE
Getting strange warnings after upgrading to 1.7.0

### ISSUE THREAD

**Issue by npearson72** [neoclide/coc-json#68]
At 1.6.1 I'm seeing the following warnings in my coc-settings.json:

<img width="634" alt="Screen Shot 2022-12-11 at 3 17 59 AM" src="https://user-images.githubusercontent.com/1323414/206898109-8c4141b8-f0dd-4a22-8a1f-441763e9586c.png">

I believe these are valid.

But after upgrading to 1.7.0, I'm getting this warning:

`Configuration property may not work as folder configuration (json)`

<img width="772" alt="Screen Shot 2022-12-11 at 3 18 24 AM" src="https://user-images.githubusercontent.com/1323414/206898130-768cebe3-8e7a-4912-ac9d-0f6bb6853e63.png">

Any idea why this is happening?

**Comment by chemzqm** [comment]
`:h coc-configuration-scope` https://github.com/neoclide/coc.nvim/discussions/4185
You should avoid use configurations with `application` scope in `.vim/coc-settings.json` of folder.
