### ISSUE TITLE
coc-json does not provide any diagnostics

### ISSUE THREAD

**Issue by Wei-Mao** [neoclide/coc-json#69]
npm list vscode-json-languageserver                                                                                      ─╯
coc-json@1.8.0 /home/harvey/.config/coc/extensions/node_modules/coc-json
└── (empty)

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
