### ISSUE TITLE
Incorrect type. Expected "array" - in package.json dependencies

### ISSUE THREAD

**Issue by pablopunk** [neoclide/coc-json#7]
![Captura de pantalla 2019-05-10 a las 17 53 08](https://user-images.githubusercontent.com/4324982/57540221-7fc77e80-734c-11e9-87bd-8b50a6284284.png)

Dependencies should be an object (just like `devDependencies`, which doesn't throw an error)

**Comment by chemzqm** [comment]
Don't know what's wrong with `vscode-json-languageservice`.

**Comment by chemzqm** [comment]
Fixed.

**Comment by pablopunk** [comment]
Awesome! Thanks @chemzqm
