### ISSUE TITLE
What options are available for `json.execArgv`?

### ISSUE THREAD

**Issue by harleypig** [neoclide/coc-json#71]
I have looked at the repository for [vscode-json-languageservice](https://www.npmjs.com/package/vscode-json-languageservice) as pointed to in the readme, and I've looked at the [Microsofts docs](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide).

I understand--I think--the services that are provided, but I don't see how I can convert those to options to pass through via the `json.execArgv` option.

Searching github provides only [one link](https://github.com/rajibahmed/coc.nvim/blob/e9d19cd05296926b1b8de21630420631c8c51317/src/extensions/json/schema.json#L21) that uses this option and it's not helpful.

So, where can I lookup what options I can pass to the language server?

**Comment by chemzqm** [comment]
It's arguments for node, not available with VSCode, use `node --help` to get valid options.

Mostly use `["--nolazy", "--inspect-brk=5858"]` to enable debugger.
